# Generated by Django 4.2 on 2023-05-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
