# Generated by Django 4.2 on 2023-05-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.IntegerField(default=6),
        ),
    ]
