# Generated by Django 4.2 on 2023-04-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='negative_prompt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='number_of_images',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='style',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
