# Generated by Django 4.2 on 2023-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_image', '0002_generatedimage_negative_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpscaledImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='upscaled_images/')),
            ],
        ),
    ]
