# Generated by Django 4.2 on 2023-04-27 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_image', '0003_upscaledimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
